/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DirBreadcrumb: typeof import('./src/components/dirBreadcrumb/DirBreadcrumb.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    FileList: typeof import('./src/components/fileList/FileList.vue')['default']
    'IEp:calendar': typeof import('~icons/ep/calendar')['default']
    'IEp:delete': typeof import('~icons/ep/delete')['default']
    'IEp:document': typeof import('~icons/ep/document')['default']
    'IEp:edit': typeof import('~icons/ep/edit')['default']
    'IEp:setting': typeof import('~icons/ep/setting')['default']
    'IEp:view': typeof import('~icons/ep/view')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    'ITabler:arrowBackUp': typeof import('~icons/tabler/arrow-back-up')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadButton: typeof import('./src/components/uploadButton/UploadButton.vue')['default']
  }
}
