/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseCheckbox: typeof import('./../src/components/base/BaseCheckbox.tsx')['default']
    BaseIcon: typeof import('./../src/components/base/BaseIcon.tsx')['default']
    BaseText: typeof import('./../src/components/base/BaseText.tsx')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElInput: typeof import('element-plus/es')['ElInput']
    FeatureBreadcrumb: typeof import('./../src/components/feature/FeatureBreadcrumb.vue')['default']
    FeatureBreadcrumbItem: typeof import('./../src/components/feature/FeatureBreadcrumbItem.vue')['default']
    FeatureCheckbox: typeof import('./../src/components/feature/FeatureCheckbox.vue')['default']
    FeatureCheckboxGroup: typeof import('./../src/components/feature/FeatureCheckboxGroup.vue')['default']
    FeatureFloatingButton: typeof import('./../src/components/feature/FeatureFloatingButton.vue')['default']
    FeatureInput: typeof import('./../src/components/feature/FeatureInput.vue')['default']
    LayoutAside: typeof import('./../src/components/layout/LayoutAside.vue')['default']
    LayoutCommonAside: typeof import('./../src/components/view/LayoutCommonAside.vue')['default']
    LayoutCommonHeader: typeof import('./../src/components/view/LayoutCommonHeader.vue')['default']
    LayoutHeader: typeof import('./../src/components/layout/LayoutHeader.vue')['default']
    OverviewFileList: typeof import('./../src/components/view/OverviewFileList.vue')['default']
    OverviewHeader: typeof import('./../src/components/view/OverviewHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
