/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonAside: typeof import('./../src/components/layout/CommonAside.vue')['default']
    CommonDialog: typeof import('./../src/components/CommonDialog.vue')['default']
    CommonHeader: typeof import('./../src/components/layout/CommonHeader.vue')['default']
    FileSystemHeader: typeof import('./../src/components/fileSystem/FileSystemHeader.vue')['default']
    FileSystemThumbnail: typeof import('./../src/components/fileSystem/FileSystemThumbnail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
