/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    DirBreadcrumb: typeof import('./../components/dirBreadcrumb/DirBreadcrumb.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FileList: typeof import('./../components/fileList/FileList.vue')['default']
    IEpBack: typeof import('~icons/ep/back')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpDelete: typeof import('~icons/ep/delete')['default']
    IEpFolderAdd: typeof import('~icons/ep/folder-add')['default']
    IEpMoon: typeof import('~icons/ep/moon')['default']
    IEpMoreFilled: typeof import('~icons/ep/more-filled')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    IEpSort: typeof import('~icons/ep/sort')['default']
    IEpSunny: typeof import('~icons/ep/sunny')['default']
    IEpUpload: typeof import('~icons/ep/upload')['default']
    IEpUserFilled: typeof import('~icons/ep/user-filled')['default']
    IIconsClose: typeof import('~icons/icons/close')['default']
    IIconsLogo: typeof import('~icons/icons/logo')['default']
    IIconsMaximize: typeof import('~icons/icons/maximize')['default']
    IIconsMinimize: typeof import('~icons/icons/minimize')['default']
    IIconsRestore: typeof import('~icons/icons/restore')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadButton: typeof import('./../components/uploadButton/UploadButton.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
